#! /bin/sh
#
# Example panel for LemonBoy's bar

COLOR_FOREGROUND='#FFebeac5'
COLOR_BACKGROUND='#FF181818'
COLOR_ACTIVE_MONITOR_FG='#FF34322E'
COLOR_ACTIVE_MONITOR_BG='#FF58C5F1'
COLOR_INACTIVE_MONITOR_FG='#FF58C5F1'
COLOR_INACTIVE_MONITOR_BG='#FF181818'
COLOR_FOCUSED_OCCUPIED_FG='#FFebeac5'
COLOR_FOCUSED_OCCUPIED_BG='#FF5C5955'
COLOR_FOCUSED_FREE_FG='#FFfdc963'
COLOR_FOCUSED_FREE_BG='#FF181818'
COLOR_FOCUSED_URGENT_FG='#FF34322E'
COLOR_FOCUSED_URGENT_BG='#FFF9A299'
COLOR_OCCUPIED_FG='#FFebeac5'
COLOR_OCCUPIED_BG='#FF181818'
COLOR_FREE_FG='#FFebeac5'
COLOR_FREE_BG='#FF181818'
COLOR_URGENT_FG='#FFF9A299'
COLOR_URGENT_BG='#FF34322E'
COLOR_LAYOUT_FG='#FFebeac5'
COLOR_LAYOUT_BG='#FF181818'
COLOR_TITLE_FG='#FFebeac5'
COLOR_TITLE_BG='#FF181818'
COLOR_STATUS_FG='#FFebeac5'
COLOR_STATUS_BG='#FF181818'

  function get_mpd_song() {
      # use mpc to get currently playing song, uppercase it
          song=$(mpc current)
          mpcpaus=$(mpc | grep "paused")

          if [[ $mpcpaus ]]; then
            echo -ne "|| "
          else
            echo -ne "> "
          fi

         echo -n $song
  }

num_mon=$(bspc query -M | wc -l)
sep="|"
while read -r line ; do

  song=$(get_mpd_song)
  vol=$(amixer get Master -M | grep -oE "[[:digit:]]*%")
  volume="Vol: $vol" 
  stat=$(insync get_status)
  if [ "$stat" = "SHARE" ]; then
    stat=$"SYNC COMPLETE"
  fi  

  syncstat="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${stat} %{B-}%{F-}"
      
	case $line in
		S*)
			# clock output
			sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
			;;
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG} ${name} %{B-}%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG} ${name} %{B-}%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${name} %{B-}%{F-}"
						;;
					L*)
						# layout
						wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
        printf "%s\n" "%{l}${wm_infos}%{c}${title}%{r} ${song}  ${sep} ${syncstat} ${sep} ${volume} ${sep} ${sys_infos}"
done
