// Extension for Chrome Browser - Magic Actions for YouTube™ - CHROMEACTIONS.COM - Copyright 2014 Vlad and Serge Strukoff - All Rights Reserved
chrome.runtime.onStartup.addListener(function(){});
(function(){function m(a){var e={ver:n,nv:3,uid:"",mwvc:!0,color:"yellow",mwvct:0,mwvci:2,gap:10,hq:!0,hqi:"large",pause:!1,plist:!1,buf:!1,buf1:!1,loop:!1,hide:!1,ha:!1,anns:!0,cin:!0,cina:!1,cini:1,cinf:!1,cinc:1,cins:"",pt:!1,pti:0,ww:!1,wide:!1,h0:!1,h1:!1,h2:!1,h3:!1,h4:!1,h5:!1,h6:!1,h7:!1,a0:!0,a1:!1,a2:!1,a3:!1,a4:!0,ui:0,c0:!1,c1:!1,c2:!1,c3:!1,f0:!0};b=a;if(void 0===b||null===b||"object"!==typeof b||void 0===b.ver)b={nv:3,uid:t()};for(var c in e)void 0===b[c]&&(b[c]=e[c]);for(c in b)void 0===
e[c]&&(delete b[c],chrome.storage.local.remove(c));for(c in b)typeof b[c]!==typeof e[c]&&(b[c]=e[c]);u();document.cookie&&-1<document.cookie.indexOf("s=1")?(l=parseInt(localStorage.st),v()):(document.cookie="s=1; expires=0; path=/",localStorage.st=l,v(),3==b.nv?w(1):b.ver!==n?(a=l,e=a+1728E6,b.nv=Math.floor(Math.random()*(e-a+1))+a,b.ver=n,h(),setTimeout(p,3E3)):0<b.nv&&b.nv<l&&w())}function v(){chrome.runtime.onMessage.addListener(A);b.a0&&b.a3&&B();setTimeout(p,2500)}function w(a){a?(b.nv=0,h(),
q({ea:"install"}),chrome.tabs.create({url:"http://www.chromeactions.com"}),chrome.tabs.create({url:"http://www.hotcleaner.com/clickclean/install-magic.html"})):(b.nv=1,h(),q({ea:"update"}),x());setTimeout(p,3E3)}function u(a){function e(c){return(Array(8).join("0")+c.toString(16)).slice(-8)}a=chrome.runtime.getURL("");var c=0,d=0,g="red LightPink orange lime GreenYellow yellow gold DodgerBlue aqua magenta DeepPink white".split(" ").indexOf(b.color),f="highres hd1440 hd1080 hd720 large medium small tiny".split(" ").indexOf(b.hqi),
c=c|b.cin<<30,c=c|b.cina<<29,c=c|b.cini<<26,c=c|b.cinf<<25,c=c|(63<b.cinc?63:b.cinc)<<19,c=c|b.h0<<18,c=c|b.h1<<17,c=c|b.h2<<16,c=c|b.h3<<15,c=c|b.h4<<14,c=c|b.h5<<13,c=c|b.h6<<12,c=c|b.h7<<11,c=c|b.a0<<10,c=c|b.a1<<9,c=c|b.a2<<8,c=c|b.a3<<7,c=c|b.a4<<6,c=c|b.ui<<5,c=c|b.c0<<4,c=c|b.c1<<3,c=c|b.c2<<2,c=c|b.c3<<1,c=c|b.f0,d=d|b.wide<<28,d=d|b.ww<<27,d=d|b.mwvc<<26,d=d|(0>g?4:g)<<22|b.mwvct<<21,d=d|b.mwvci<<19,d=d|b.gap<<14,d=d|b.hq<<13,d=d|(0>f?3:f)<<10,d=d|b.pause<<9,d=d|b.plist<<8,d=d|b.buf<<7,d=
d|b.buf1<<6,d=d|b.loop<<5,d=d|b.hide<<4,d=d|b.ha<<3,d=d|b.anns<<2,d=d|b.pt<<1,d=d|b.pti;a="0"+e(c)+e(d)+a+(62<b.cinc?b.cins:"");r='var e=document.createEvent("CustomEvent");e.initCustomEvent("mafy",!1,!1,"'+a+'");window.dispatchEvent(e);if(window.sessionStorage)window.sessionStorage.mafy="'+a+'"'}function h(){b.a0&&b.a4||(b.ui=0);try{chrome.storage.local.set(b)}catch(a){y(a,1)}try{localStorage.setItem("opt",JSON.stringify(b))}catch(e){y(e,1)}u(1);chrome.tabs.query({windowType:"normal",url:"*://*.youtube.com/*",
status:"complete"},function(c){for(var a=0,b=c.length;a<b;a++)chrome.tabs.executeScript(c[a].id,{code:r.replace('"0','"1')})})}function A(a,e,c){32==a&&(chrome.tabs.executeScript(e.tab.id,{code:r,runAt:"document_start"}),chrome.pageAction.show(e.tab.id));try{a=JSON.parse(a)}catch(d){return}0==a.id?c(b):1==a.id?q(a.ga):2==a.id?chrome.tabs.create({url:a.url}):3==a.id?(b=a.opt,h()):4==a.id?(b[a.name]=a.value,h()):5==a.id?c({value:b[a.name]}):6==a.id?C(a.v):7==a.id?x():9==a.id?c(z):11==a.id&&chrome.windows.update(e.tab.windowId,
{state:a.v?"fullscreen":"maximized"})}function C(a){chrome.windows.getLastFocused({populate:!1},function(b){z={w:a[0],h:a[1],pic:a[2],vid:a[3],lic:a[4],t:a[5]};chrome.tabs.query({url:"http://www.chromeactions.com/capture-snapshot-video-frames.html"},function(a){a&&a.length?chrome.tabs.update(a[0].id,{active:!0},function(){chrome.tabs.executeScript(a[0].id,{file:"cap6830.js"})}):chrome.tabs.create({active:!0,url:"http://www.chromeactions.com/capture-snapshot-video-frames.html"})})})}function x(){var a,
b="opt.html?s=7"+(new Date).getDate(),c=navigator.onLine?"http://www.chromeactions.com/magic-actions-for-youtube-chrome-app.html":b;if(k&&k.url===c)chrome.tabs.update(k.id,{active:!0},function(a){k=a});else{chrome.tabs.create({url:c,active:!0},function(c){k=c;chrome.windows.update(c.windowId,{focused:!0});a=c.id;d()});var d=function(){chrome.tabs.get(a,function(c){"complete"==c.status?0>c.title.indexOf("Magic")&&chrome.tabs.update(a,{url:b}):setTimeout(d,1E3)})}}}function y(a,b){console.log("Magic: "+
["Could't read preferences.","Could't write preferences."][b]+" "+a.name+": "+a.message)}function D(a,b){if(7840==a.menuItemId){var c="http://www.youtube.com/results?search_query="+encodeURIComponent(a.selectionText);0==b.url.indexOf("http://www.youtube.com/")?chrome.tabs.update({url:c}):chrome.tabs.create({url:c,selected:!0})}}function B(){chrome.contextMenus.create({id:"7840",title:"Search YouTube for %s",contexts:["selection"]},function(){chrome.contextMenus.onClicked.addListener(D)})}function p(){s("GET",
"manifest.json",null,"responseText",function(a){if(a){try{a=JSON.parse(a)}catch(b){return}s("GET",a.update_url+"?x=id%3Dabjcfabbhafbcdfjoecdgepllmpfceif%26v%3D"+a.version+"%26uc",null,"responseXML",function(a){})}})}function q(a){var e=a.ec?a.ec:"app",c=a.ea?a.ea:"unk";a=a.el?a.el:"mafy 6.8.3";b.uid||(b.uid=t());s("POST","http://www.google-analytics.com/collect","v=1&tid=UA-326771-7&cid="+b.uid+"&t=event&ec="+e+"&ea="+c+"&el="+a,"response",function(){})}function s(a,b,c,d,g){var f=new XMLHttpRequest;
f.onload=function(a){200==this.status?g(this[d]):g()};f.onerror=g;f.onabort=g;f.open(a,b,!0);f.send(c)}function t(){var a=Math.random,b=(4294967296*a()>>>0).toString(16),c=((4294967296*a()&4294922239|16384)>>>0).toString(16),d=((4294967296*a()&3221225471|2147483648)>>>0).toString(16),a=(4294967296*a()>>>0).toString(16);8>b.length&&(b=("0000000"+b).slice(-8));8>c.length&&(c=("0000000"+c).slice(-8));8>d.length&&(d=("0000000"+d).slice(-8));8>a.length&&(a=("0000000"+a).slice(-8));return[b,c.slice(0,4),
c.slice(4),d.slice(0,4),d.slice(4)+a].join("-")}var n="6.8.3",l=Date.now(),z,b,r,k;chrome.storage.local.get(null,function(a){if(chrome.runtime.lastError)if(a=localStorage.getItem("opt"),void 0===a)m();else{try{a=JSON.parse(a)}catch(b){a=void 0}m(a)}else m(a)})})();
