// Extension for Chrome Browser - Magic Actions for YouTube™ - CHROMEACTIONS.COM - Copyright 2014 Vlad and Serge Strukoff - All Rights Reserved
var bLocalPage="chrome-extension:"===window.location.protocol?!0:!1;bLocalPage&&window.location.search!="?s=7"+(new Date).getDate()?window.location.href="options.html":magicOpt();
function magicOpt(){function F(){d("prf2")?G():setTimeout(F,200)}function G(){chrome.runtime.sendMessage('{"id":0}',function(a){if(a){var e=d("prf"),t=d("prf2"),c;if(e){if(0<a.nv){if(c=d("m0"))c.textContent=chrome.i18n.getMessage("m1",[C,a.ver]),c.style.display="block";k("nv",0)}c=g("h3");c.textContent=C+" v"+a.ver+" "+b("m2");e.appendChild(c);c=g("p");c.id="m2";c.appendChild(document.createTextNode(chrome.i18n.getMessage("m3",C)));e.appendChild(c);c=g("ul");c.id="opt";e.appendChild(c);f(c,"mwvc",
b("o8"),a.mwvc,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-volume-control.html");v=a.mwvct;var e=c,h=g("li");h.id="mwvct";h.className="sub";h.setAttribute("disabled",!d("mwvc").checked);e.appendChild(h);n(h,"vt0",b("o82"),H);n(h,"vt1",b("o83"),H);d("vt"+v).checked=!0;r=a.color;e=g("li");h=g("label");e.className="sub";e.setAttribute("disabled",!d("mwvc").checked);e.id="color";h.textContent=b("o9");e.appendChild(h);d("opt").appendChild(e);l("red");l("LightPink");l("orange");l("lime");
l("GreenYellow");l("yellow");l("gold");l("DodgerBlue");l("aqua");l("magenta");l("DeepPink");l("white");(h=d(r))||(r="lime");d(r).className="sel";w=a.mwvci;var e=c,h=g("li"),z=g("label");h.id="mwvci";h.className="sub";h.setAttribute("disabled",!d("mwvc").checked);z.textContent=b("o23");h.appendChild(z);e.appendChild(h);n(h,"vc1",b("o24"),D);n(h,"vc2",b("o25"),D);n(h,"vc0",b("o26"),D);d("vc"+w).checked=!0;var e=b("o27"),h=a.gap,z=!d("mwvc").checked,u=g("li"),m=g("label"),p=g("input");m.textContent=
e;m.setAttribute("for","gap");p.type="range";p.min=1;p.max=25;p.step=1;p.value=h;p.id="gap";p.title="Range: 1-25";u.appendChild(m);u.appendChild(p);m=g("span");m.textContent=h;u.appendChild(m);u.className="sub";u.setAttribute("disabled",z);d("opt").appendChild(u);p.addEventListener("change",J,!1);f(c,"hq",b("o90"),a.hq,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-autohd.html");s=a.hqi;e=g("li");e.id="hqi";e.className="sub";e.setAttribute("disabled",!d("hq").checked);d("opt").appendChild(e);
q("highres",b("o91"));q("hd1440",b("o92"));q("hd1080",b("o93"));q("hd720",b("o94"));q("large",b("o95"));q("medium",b("o96"));q("small",b("o97"));q("tiny",b("o98"));(e=d(s))||(s="highres");d(s).checked=!0;t&&(c=g("ul"),c.id="opt2",t.appendChild(c));f(c,"ha",b("o20"),a.ha);f(c,"wide",b("o28"),a.wide);f(c,"ww",b("o80"),a.ww);f(c,"cin",b("o29"),a.cin,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-cinema.html");x=a.cini;t=c;e=g("li");h=g("label");e.id="cini";e.className="sub";e.setAttribute("disabled",
!d("cin").checked);h.textContent=b("o32");e.appendChild(h);t.appendChild(e);n(e,"ca0",b("o33"),E);n(e,"ca1",b("o34"),E);n(e,"ca2",b("o35"),E);d("ca"+x).checked=!0;f(c,"cina",b("o30"),a.cina,1,!d("cin").checked);f(c,"cinf",b("o31"),a.cinf,1,!d("cin").checked);f(c,"pt",b("o65"),a.pt);A("pt");y=a.pti;t=c;e=g("li");e.id="pti";e.className="sub";e.setAttribute("disabled",!d("pt").checked);t.appendChild(e);n(e,"pt0",b("o66"),I);n(e,"pt1",b("o67"),I);d("pt"+y).checked=!0;f(c,"pause",b("o17"),a.pause);f(c,
"plist",b("o19"),a.plist,1,!d("pause").checked);f(c,"buf",b("o18"),a.buf);f(c,"buf1",b("o63"),a.buf1,1,!d("buf").checked);f(c,"loop",b("o40"),a.loop);f(c,"hide",b("o41"),a.hide);f(c,"c0",b("o70"),a.c0,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-comments.html");f(c,"c1",b("o71"),a.c1,1,!d("c0").checked);f(c,"c2",b("o72"),a.c2,1,!d("c0").checked);f(c,"c3",b("o73"),a.c3,1,!d("c0").checked);f(c,"anns",b("o42"),a.anns);f(c,"f0",b("o43"),a.f0);d("f0").parentElement.title="Show/Hide the Filters button so you can apply a filter (grayscale, flip, high contrast etc.) to any video";
A("f0");f(c,"h0",b("o50"),a.h0);f(c,"h7",b("o56"),a.h7,1,!d("h0").checked);A("h7");f(c,"h1",b("o51"),a.h1,1,!d("h0").checked);f(c,"h2",b("o52"),a.h2,1,!d("h0").checked);f(c,"h3",b("o53"),a.h3,1,!d("h0").checked);f(c,"h4",b("o54"),a.h4,1,!d("h0").checked);f(c,"h5",b("o55"),a.h5,1,!d("h0").checked);f(c,"h6",b("o64"),a.h6,1,!d("h0").checked);f(c,"a0",b("o60"),a.a0,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-themes.html");f(c,"a1",b("o61"),a.a1,1,!d("a0").checked);f(c,"a2",b("o62"),a.a2,
1,!d("a0").checked);f(c,"a3",b("o84"),a.a3,1,!d("a0").checked);A("a3");f(c,"a4",b("o81"),a.a4,1,!d("a0").checked)}}else setTimeout(G,500)})}function k(a,e){chrome.runtime.sendMessage(JSON.stringify({id:4,name:a,value:e}))}function A(a){var e=g("sup");e.textContent=b("m4");e.style.color="red";e.style.verticalAlign="top";d(a).nextElementSibling.appendChild(e)}function K(a){d(r).className="";r=this.id;this.className="sel";k("color",r)}function H(a){d("vt"+v).checked=!1;v=parseInt(this.id.charAt(2));
this.checked=!0;k("mwvct",v)}function D(a){d("vc"+w).checked=!1;w=parseInt(this.id.charAt(2));this.checked=!0;k("mwvci",w)}function E(a){d("ca"+x).checked=!1;x=parseInt(this.id.charAt(2));this.checked=!0;k("cini",x)}function I(a){d("pt"+y).checked=!1;y=parseInt(this.id.charAt(2));this.checked=!0;k("pti",y)}function L(a){d(s).checked=!1;s=this.id;this.checked=!0;k("hqi",s)}function M(a){k(this.id,this.checked);a=this.parentElement;if("sub"!=a.className)for(a=a.nextElementSibling;a&&"sub"==a.className;)a.setAttribute("disabled",
!this.checked),a=a.nextElementSibling}function N(a){k(a.id,parseInt(a.value))}function J(a){B&&(clearTimeout(B),B=0);this.nextElementSibling.textContent=this.value;B=setTimeout(N,1E3,this)}function l(a){var e=g("button");e.id=a;e.style.backgroundColor=a;d("color").appendChild(e);e.addEventListener("click",K,!1)}function n(a,e,b,c){var d=g("label"),f=g("input");f.type="radio";f.id=e;a.appendChild(f);d.textContent=b;d.setAttribute("for",e);a.appendChild(d);f.addEventListener("click",c,!1)}function q(a,
e){var b=d("hqi"),c=g("label"),f=g("input");f.type="radio";f.id=a;b.appendChild(f);c.textContent=e;c.setAttribute("for",a);b.appendChild(c);f.addEventListener("click",L,!1)}function f(a,b,d,c,f,l,n){var m=g("li"),p=g("label"),k=g("input");p.textContent=d;p.setAttribute("for",b);k.type="checkbox";k.id=b;k.checked=c;m.appendChild(k);m.appendChild(p);f?(m.className="sub",m.setAttribute("disabled",l)):m.className="opt";n&&(b=g("a"),b.href=n,b.setAttribute("target","_blank"),b.className="help",m.appendChild(b));
a.appendChild(m);k.addEventListener("click",M,!1)}function d(a){return document.getElementById(a)}function g(a){return document.createElement(a)}function b(a){return chrome.i18n.getMessage(a)}var r,s,v,w,x,y,B=0,C=chrome.i18n.getMessage("extName");F()};
